- name: priority/P0
  color: d73a4a
  description: Bloquea entregas o SLO
- name: priority/P1
  color: b60205
  description: Importante en el milestone actual
- name: priority/P2
  color: fbca04
  description: Normal
- name: priority/P3
  color: c5def5
  description: Nice-to-have

- name: type/bug
  color: d73a4a
- name: type/feature
  color: a2eeef
- name: type/chore
  color: cccccc
- name: type/docs
  color: 0075ca
- name: type/task
  color: 0366d6
- name: type/spike
  color: 5319e7

- name: area/frontend
  color: 0e8a16
- name: area/backend
  color: 1d76db
- name: area/data
  color: 5319e7
- name: area/devops
  color: 0052cc
- name: area/nlp
  color: 8a2be2
- name: area/etl
  color: 6f42c1

- name: status/needs-info
  color: fef2c0
- name: status/ready
  color: 0e8a16
- name: status/blocked
  color: b60205
- name: status/in-review
  color: 5319e7
- name: status/done
  color: 2cbe4e

- name: security
  color: 8b0000
- name: privacy
  color: 9400d3
- name: migration
  color: 000000
- name: breaking-change
  color: 8b4513
