pre-commit:
  parallel: true
  commands:
    lint-staged:
      run: pnpm dlx lint-staged
    typecheck-web:
      # Sólo si hay archivos TS/TSX staged en apps/web/
      files:
        - apps/web/**/*.{ts,tsx}
      run: pnpm -C apps/web typecheck
      stage_fixed: false

commit-msg:
  commands:
    commitlint:
      run: pnpm dlx commitlint --edit "$1"
      skip:
        - merge
        - rebase
