blank_issues_enabled: false
contact_links:
  - name: Preguntas generales
    url: https://github.com/<ORG_OR_USER>/<REPO>/discussions
    about: Usa Discussions para dudas no técnicas o brainstorming.
